app/shared/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from .connection import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False, unique=True)
    slug = db.Column(db.String(255), nullable=False, unique=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    content = db.Column(db.UnicodeText, nullable=False)
    date = db.Column(db.Date, nullable=False)

    #relationship property
    category = db.relationship('Category', backref=db.backref('posts', lazy='dynamic'))


    def __repr__(self):
        return self.title


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False, unique=True)


    def __repr__(self):
        return self.name


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    username = db.Column(db.String(100), nullable=False, unique=True)
    pwdhash = db.Column(db.String(255), nullable=False)


    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.pwdhash = generate_password_hash(password)


    def check_password(self, password):
        return check_password_hash(self.pwdhash, password)


    def is_authenticated(self):
        return True


    def is_active(self):
        return True


    def is_anonymous(self):
        return False


    def get_id(self):
        return unicode(self.id)

app/shared/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, EqualTo


class LoginForm(Form):
	username = TextField('Username', [InputRequired()])
	password = PasswordField('Password', [InputRequired()])

app/__init__.py
# flask and extensions imports
from flask import Flask, url_for, request
from flask.ext.script import Manager
from flask.ext.migrate import Migrate, MigrateCommand
from flask.ext.login import LoginManager
from flask.ext.admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_debugtoolbar import DebugToolbarExtension
from flask.ext.restless import APIManager

# user defined module imports
from app.shared.connection import db
from app.shared.models import User, Category, Post

# blueprint imports
from app.frontend.views import frontend
from app.auth.views import auth
from app.admin.views import UserAdminView, PostAdminView, CategoryAdminView, MyAdminIndexView


# create app object
app = Flask(__name__)
app.config.from_object('app.shared.configuration.DevelopmentConfig')

# setup db
db.init_app(app)

# create database tables within app context
with app.app_context():
	db.create_all()

# setup migration
migrate = Migrate(app, db)

# setup manage script
script = Manager(app)
script.add_command('db', MigrateCommand)

# setup login
login = LoginManager()
login.init_app(app)
login.login_view = 'auth.login'

@login.user_loader
def load_user(id):
	return User.query.get(int(id))

# setup admin panel
admin = Admin(app, template_mode='bootstrap3', index_view=MyAdminIndexView())

admin.add_view(UserAdminView(User, db.session))
admin.add_view(CategoryAdminView(Category, db.session))
admin.add_view(PostAdminView(Post, db.session))

# setup debug toolbar
toolbar = DebugToolbarExtension(app)

# setup api
api = APIManager(app, flask_sqlalchemy_db=db)

# create api blueprint within app context
with app.app_context():
	api.create_api(Category, methods=['GET', 'POST', 'DELETE'])
	api.create_api(Post, methods=['GET', 'POST', 'DELETE'])

# register all blueprints
app.register_blueprint(frontend)
app.register_blueprint(auth)

@app.before_request
def option_autoreply():
    if request.method == 'OPTIONS':
        resp = app.make_default_options_response()
        
        headers = None
        if 'ACCESS_CONTROL_REQUEST_HEADERS' in request.headers:
            headers = request.headers['ACCESS_CONTROL_REQUEST_HEADERS']
            
        h = resp.headers
        
        h['Access-Control-Allow-Origin'] = request.headers['Origin']
        h['Access-Control-Allow-Methods'] = request.headers['Access-Control-Request-Methods']
        h['Access-Control-Max-Age'] = "10"
        
        if headers is not None:
            h['Access-Control-Allow-Headers'] = headers
            
        return resp
        

@app.after_request
def set_allow_origin(resp):
    h = resp.headers
    
    if request.method != 'OPTIONS' and 'Origin' in request.headers:
        h['Access-Control-Allow-Origin'] = request.headers['Origin']
        
    return resp

app/admin/views.py
from flask import redirect, url_for, request
from flask_admin.contrib.sqla import ModelView
from flask.ext.admin import AdminIndexView
from wtforms import PasswordField
from wtforms.validators import InputRequired
from flask.ext.login import current_user

from .widgets import CKTextAreaField

class BaseAdminView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated


    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('auth.login', next=request.path))


class MyAdminIndexView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated


    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('auth.login', next=request.path))


class UserAdminView(BaseAdminView):
    column_searchable_list = ('username', 'email')
    column_sortable_list = ('username', 'email')
    column_exclude_list = ('pwdhash',)
    form_excluded_columns = ('pwdhash',)
    form_edit_rules = ('username', 'email')


    def scaffold_form(self):
        form_class = super(UserAdminView, self).scaffold_form()
        form_class.password = PasswordField('Password', [InputRequired()])
        return form_class


    def create_model(self, form):
        model = self.model(form.email.data, form.username.data, form.password.data)
        form.populate_obj(model)
        self.session.add(model)
        self._on_model_change(form, model, True)
        self.session.commit()


class PostAdminView(BaseAdminView):
    column_exclude_list = ('content',)
    form_overrides = {
        'content': CKTextAreaField
    }
    create_template = 'ckeditor.html'
    edit_template = 'ckeditor.html'


class CategoryAdminView(BaseAdminView):
    form_excluded_columns = ('posts',)

app/frontend/views.py
from flask import Blueprint, render_template, request, make_response, current_app, url_for
from flask.ext.login import login_required
from app.shared.models import Category, Post


frontend = Blueprint('frontend', __name__)


@frontend.context_processor
def ctx_processor():
	categories = Category.query.all()
	categories_right = categories[:len(categories)/2]
	categories_left = categories[len(categories)/2:]
	
	return {
		'categories_left': categories_left,
		'categories_right': categories_right
	}


@frontend.route('/')
def index():
	page = int(request.args.get('page', 1))
	posts = Post.query.order_by(Post.date.desc()).paginate(page, 10)
	return render_template('index.html', posts=posts)


@frontend.route('/post/<int:id>')
def post(id):
	post = Post.query.get_or_404(id)
	return render_template('post.html', post=post)


@frontend.route('/about')
def about():
	return render_template('about.html')


@frontend.route('/category/<int:id>')
def category(id):
	category = Category.query.get_or_404(id)
	posts = Post.query.filter_by(category_id=id).all()
	return render_template('category.html', category=category, posts=posts)

@frontend.route('/search')
def search():
	q = request.args.get('q')
	posts = Post.query.filter_by(title=q).order_by(Post.date.desc()).all()
	return render_template('search.html', posts=posts)


@frontend.route('/upload', methods=['POST'])
@login_required
def upload():
	import os
	error = url = ""
	callback = request.args.get('CKEditorFuncNum')
	
	if request.method == 'POST' and 'upload' in request.files:
		image = request.files['upload']
		filepath = os.path.join(current_app.static_folder, 'uploads', image.filename)
		dirname = os.path.dirname(filepath)
		
		if not os.path.exists(dirname):
			try:
				os.makedirs(dirname)
			except:
				error = 'ERROR_CREATING_DIR'
		elif not os.access(dirname, os.W_OK):
			error = 'ERROR_DIR_NOT_WRITEABLE'

		if not error:
			image.save(filepath)
			url = url_for('static', filename="%s/%s" % ('uploads', image.filename))
		else:
			error = 'ERROR_POST'

		res = """<script type="text/javascript">
					window.parent.CKEDITOR.tools.callFunction(%s, '%s', '%s');
				 </script>""" % (callback, url, error)

	 	response = make_response(res)
	 	response.headers['Content-Type'] = 'text/html'
	 	return response

app/templates/_macros.html
{% macro alert() -%}
	{% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
{%- endmacro  %}

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
	<h1>About Me</h1>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Rooco's Python Blog">
    <meta name="author" content="Rully Ramanda">

    <title>Rooco's Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/blog.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('frontend.index') }}">Rooco's Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ url_for('frontend.about') }}">About</a>
                    </li>
                </ul>
                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/admin">Admin</a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                </ul>
                {% endif %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    {% block page_heading %}Rooco's Blog{% endblock %}
                    <small>{% block secondary_text %}{% endblock %}</small>
                </h1>

                {% block content %}{% endblock %}

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                {% for cat in categories_left %}
                                    <li><a href="{{ url_for('frontend.category', id=cat.id) }}">{{ cat.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                {% for cat in categories_right %}
                                    <li><a href="{{ url_for('frontend.category', id=cat.id) }}">{{ cat.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Rooco's Blog 2015</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>

</html>

app/templates/category.html
{% extends 'base.html' %}

{% block page_heading %}
	Posts in {{ category.name }}
{% endblock %}

{% block content %}
	{% for post in posts %}
		<h2><a href="{{ url_for('frontend.post', id=post.id) }}">{{ post.title }}</a></h2>
        <p class="lead">by <span>Start Bootstrap</span></p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
        <hr>
        <p>{{ post.content }}</p>
        <a class="btn btn-primary" href="{{ url_for('frontend.post', id=post.id) }}">
        	Read More <span class="glyphicon glyphicon-chevron-right"></span>
    	</a>

        <hr>
	{% endfor %}
{% endblock %}

app/templates/ckeditor.html
{% extends 'admin/model/edit.html' %}

{% block tail %}
	{{ super() }}
	<script src="{{ url_for('static', filename='js/ckeditor/ckeditor.js') }}"></script>
	<script>
		CKEDITOR.replace('ckeditor');
	</script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
	{% for post in posts.items %}
		<h2><a href="{{ url_for('frontend.post', id=post.id) }}">{{ post.title }}</a></h2>
        <p class="lead">by <span>Rooco</span></p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.date }}</p>
        <hr>
        <p>{{ post.content }}</p>
        <a class="btn btn-primary" href="{{ url_for('frontend.post', id=post.id) }}">
        	Read More <span class="glyphicon glyphicon-chevron-right"></span>
    	</a>

        <hr>
	{% endfor %}

    <!-- Pager -->
    <ul class="pager">
        {% if posts.has_next %}
        <li class="previous">
            <a href="{{ url_for('frontend.index', page=posts.next_num) }}">&larr; Older</a>
        </li>
        {% endif %}
        {% if posts.has_prev %}
        <li class="next">
            <a href="{{ url_for('frontend.index', page=posts.prev_num) }}">Newer &rarr;</a>
        </li>
        {% endif %}
    </ul>
{% endblock %}

app/templates/login.html
{% from '_macros.html' import alert %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Rooco's Python Blog">
    <meta name="author" content="Rully Ramanda">

    <title>Rooco's Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/blog.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="panel panel-primary" style="width:50%;margin:auto;">
                <div class="panel-heading">
                    <h3 class="panel-title">Login</h3>
                </div>
                <div class="panel-body">
                    <div>
                        {{ alert() }}
                    </div>
                    <form action="{{ request.url }}" method="post" role="form">
                        
                        {{ form.csrf_token }}

                        <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                            {{ form.username.label }}
                            {{ form.username(class='form-control') }}
                            {% if form.username.errors %}
                                {% for error in form.username.errors %}
                                <span class="help-block">{{ error }}</span>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                            {{ form.password.label }}
                            {{ form.password(class="form-control") }}
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}
                                <span class="help-block">{{ error }}</span>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <button class="btn btn-default" type="submit">Login</button>
                    </form>
                </div>
            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>

</html>

app/templates/post.html
{% extends 'base.html' %}

{% block page_heading %}{{ post.title }}{% endblock %}

{% block content %}
	<!-- Author -->
    <p class="lead">
        by <a href="#">Rooco</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ post.date }}</p>

    <hr>

    <!-- Post Content -->
    <p>{{ post.content }}</p>

    <hr>

    <!-- Blog Comments -->

    <!-- Comments Form -->
    <div class="well">
        <h4>Leave a Comment:</h4>
        <form role="form">
            <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
    </div>

    <!-- Comment -->
    <div class="media">
        <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            <!-- Nested Comment -->
            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Nested Start Bootstrap
                        <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
            </div>
            <!-- End Nested Comment -->
        </div>
    </div>
{% endblock %}